# Generated by Django 5.1.1 on 2024-10-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProviderId', models.IntegerField()),
                ('ProductId', models.IntegerField()),
                ('ProductCategory', models.CharField(choices=[('financial_services', 'Financial Services'), ('airtime', 'Airtime'), ('utility_bill', 'Utility Bill'), ('data_bundles', 'Data Bundles'), ('tv', 'TV'), ('ticket', 'Ticket'), ('movies', 'Movies'), ('transport', 'Transport'), ('other', 'Other')], max_length=100)),
                ('ChannelId', models.IntegerField()),
                ('Amount', models.FloatField()),
                ('Transaction_Hour', models.IntegerField()),
                ('Transaction_Day', models.IntegerField()),
                ('Average_transaction_amount', models.FloatField()),
                ('STD_Transaction_Amount', models.FloatField()),
                ('Transaction_Month', models.IntegerField()),
            ],
        ),
    ]
